- name: blocked
  description: Work on this issue is currently blocked
  color: "ff0000"
- name: bug
  description: Something isn't working
  color: "d73a4a"
- name: dependencies
  description: Dependency file updates
  color: "0366d6"
- name: documentation
  description: Improvements or additions to documentation
  color: "0075ca"
- name: duplicate
  description: This issue or pull request already exists
  color: "cfd3d7"
- name: enhancement
  description: New feature or request
  color: "a2eeef"
- name: good first issue
  description: Good for newcomers
  color: "7057ff"
- name: hacktoberfest-accepted
  description: This pull request has been accepted for Hacktoberfest
  color: "D93F0B"
- name: help wanted
  description: We are asking the community to submit a PR to resolve this issue
  color: "008672"
- name: new table
  description: New table request
  color: "006b75"
- name: "priority:high"
  description: This issue requires immediate attention
  color: "DB421D"
- name: "priority:low"
  description: This issue can be worked on at any time
  color: "6F9FBA"
- name: "priority:medium"
  description: This issue should be worked on for an upcoming release
  color: "E3DA48"
- name: review
  description: Triggers a workflow to review and validate queries
  color: "d876e3"
- name: stale
  description: No recent activity has been detected on this issue/PR and it will be closed
  color: "eb7134"
- name: aws
  description: AWS plugin issues
  color: "cfd3d7"
- name: azure
  description: Azure plugin issues
  color: "cfd3d7"
- name: gcp
  description: GCP plugin issues
  color: "cfd3d7"
- name: tailpipe
  description: Tailpipe plugin issues
  color: "8E44AD"
- name: steampipe
  description: Steampipe plugin issues
  color: "2ECC40"
- name: github
  description: GitHub plugin issues
  color: "cfd3d7"
- name: jira
  description: Jira plugin issues
  color: "cfd3d7"
- name: oci
  description: OCI plugin issues
  color: "cfd3d7"
- name: cloudflare
  description: Cloudflare plugin issues
  color: "cfd3d7"
- name: datadog
  description: Datadog plugin issues
  color: "cfd3d7"
- name: wiz
  description: Wiz plugin issues
  color: "cfd3d7"
- name: jira
  description: Jira plugin issues
  color: "cfd3d7"
- name: digitalocean
  description: DigitalOcean plugin issues
  color: "cfd3d7"
- name: azuread
  description: AzureAD plugin issues
  color: "cfd3d7"
- name: crowdstrike
  description: CrowdStrike plugin issues
  color: "cfd3d7"
