name: AWS Export Tool Linux Build Artifact - AMD64

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch that will be used to create the Linux AMD64 build"
        required: true
      version:
        description: "Version"
        required: true

# env:
#   PLUGIN_NAME: steampipe-plugin-aws

jobs:
  build-export-tool:
    name: Build Export Tool
    # needs: get-version
    runs-on:
      group: large-runners

    steps:
      - name: Set environment variables
        run: |
          plugin_name=$(echo $GITHUB_REPOSITORY | cut -d'-' -f 3)
          echo $plugin_name
          echo "PLUGIN_NAME=${plugin_name}" >> $GITHUB_ENV

      - name: Get latest version tag
        run: |-
          echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "Version: ${VERSION}"

      - name: If workflow_dispatch, get version from input
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          else
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          fi
          echo "Version: ${VERSION}"

      - name: Check out steampipe-export
        uses: actions/checkout@v2
        with:
          repository: "turbot/steampipe-export"
          ref: ${{ github.event.inputs.branch }}

      - name: Setup GoLang
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Fetch plugin module
        run: go get github.com/turbot/steampipe-plugin-aws@v0.138.0

      - name: Build steampipe-export
        run: |
          pwd
          ls -ltr
          make build plugin=aws
          ls -ltr
          go mod tidy

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          install-only: true

      - name: Run GoReleaser
        run: |
          ./scripts/release.sh

      - name: Copy the gzipped binaries from dist
        run: |-
          ls -al dist/
          cp dist/steampipe_export_aws.linux_amd64.tar.gz steampipe_export_aws.linux_amd64.tar.gz
          ls -al

      - name: Save Linux Build Artifact - AMD64
        uses: actions/upload-artifact@v4
        with:
          name: steampipe_export_aws.linux_amd64.tar.gz
          path: steampipe_export_aws.linux_amd64.tar.gz
          if-no-files-found: error


