name: Sync Labels
on:
  workflow_call:
    inputs:
      dryRun:
        description: Set to true for a dry run
        required: false
        default: "false"
        type: string

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: EndBug/label-sync@v2
        with:
          config-file: 'https://raw.githubusercontent.comturbot/steampipe-workflows/blob/main/.github/labels.yml'
          delete-other-labels: false
          dry-run: ${{ inputs.dryRun }}
